export const LOADING = {
  LOADING_BEGIN: "LOADING_BEGIN",
  LOADING_COMPLETE: "LOADING_COMPLETE",
  LOADING_FAILED: "LOADING_FAILED"
};

export const STATUS = {
  HANDLE_STATUS_ERROR_SUCCESS: "HANDLE_STATUS_ERROR_SUCCESS",
  HANDLE_STATUS_RESET_SUCCESS: "HANDLE_STATUS_RESET_SUCCESS"
};

export const USER = {
  USER_INFO_BEGIN: "USER_INFO_BEGIN",
  USER_INFO_SUCCESS: "USER_INFO_SUCCESS",
  USER_INFO_FAILED: "USER_INFO_FAILED",
  USER_UPDATE_BEGIN: "USER_UPDATE_BEGIN",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  USER_VERIFY_OR_CREATE_FROM_AUTH0_BEGIN:
    "USER_VERIFY_OR_CREATE_FROM_AUTH0_BEGIN",
  USER_VERIFY_OR_CREATE_FROM_AUTH0_SUCCESS:
    "USER_VERIFY_OR_CREATE_FROM_AUTH0_SUCCESS",
  USER_VERIFY_OR_CREATE_FROM_AUTH0_FAILED:
    "USER_VERIFY_OR_CREATE_FROM_AUTH0_FAILED",
  USER_RESET: "USER_RESET"
};

export const SESSION = {
  LOGGED_BEGIN: "LOGGED_BEGIN",
  LOGGED_COMPLETE: "LOGGED_COMPLETE"
};
